---
name: "JellyNext"
guid: "a4df60c5-6ab4-412a-8f79-2cab93fb2bc5"
version: "1.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
owner: "jellynext"
overview: "Trakt-powered discovery with per-user virtual libraries and one-click download integration for Radarr/Sonarr"
description: >
  JellyNext delivers personalized Trakt-powered discovery directly inside Jellyfin by creating per-user virtual libraries for:
  - Trakt Recommendations
  - New Seasons available for followed series

  Features:
  - Per-user Trakt account linking
  - Virtual recommendation and new seasons libraries
  - One-click download triggers to Radarr/Sonarr
  - Smart Play/Download button switching
  - Automatic metadata enrichment via TMDB
category: "General"
artifacts:
  - "Jellyfin.Plugin.JellyNext.dll"
build_type: "dotnet"
dotnet_configuration: "Release"
dotnet_framework: "net8.0"
